Add billingOptions type and availableCountries
vtex-apps/cookie-script pull request #3
Opened 2020-08-13 04:01 UTC by marlonguimaraes

Please, check the description of the PR https://github.com/vtex-apps/google-customer-reviews/pull/7 to understand the context and the changes requested here.

2020-08-13 14:09 UTC, manoel-gumes approved these changes

2020-08-13 20:39 UTC, arturpimentel approved these changes

2020-09-15 17:12 UTC, klzns approved these changes

2020-09-15 17:12 UTC, klzns requested changes
Must be rebased

2020-09-15 19:56 UTC, klzns approved these changes

2020-09-15 20:31 UTC, merged