full_description adjustments
vtex-apps/cookie-script pull request #4
Opened 2020-08-13 19:56 UTC by manoel-gumes

**What problem is this solving?**

Novo formato para full_description.txt para publicação na App Store

**How should this be manually tested?**

**Screenshots or example usage:**

2020-08-13 20:17 UTC, fabianaferreira approved these changes
LGTM

2020-09-15 17:12 UTC, klzns approved these changes

2020-09-15 17:12 UTC, klzns requested changes
Must be rebased

2020-09-15 21:18 UTC, klzns approved these changes

2022-08-11 09:03 UTC, mihainutiu-vtex approved these changes
LGTM

2024-05-20 07:15 UTC, mihainutiu-vtex approved these changes

2024-05-20 07:15 UTC, merged